version: '2'
services:
  nginx:
    image: nginx
    volumes:
      - ./frontEnd/dist/:/var/www/
      - ./sites-enabled/default:/etc/nginx/conf.d/default.conf
    environment:
     - NGINX_PORT=80
    links:
      - "web:web"
    ports:
      - "80:80"
  mongo:
    image: mongo
  web:
    build: ./backEnd
    command:  npm start
    volumes:
      - ./backEnd/bin:/app/bin
      - ./backEnd/config:/app/config
      - ./backEnd/middleware:/app/middleware
      - ./backEnd/models:/app/models
      - ./backEnd/routes:/app/routes
    ports:
      - "3000:3000"
    links:
      - "mongo:mongo"
